In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
# Load datasets
transactions = pd.read_csv("transaction_data.csv")
products = pd.read_csv("product.csv")
demographics = pd.read_csv("hh_demographic.csv")

print("Transaction Shape:", transactions.shape)
print("Product Shape:", products.shape)
print("Demographic Shape:", demographics.shape)

Transaction Shape: (2595732, 12)
Product Shape: (92353, 7)
Demographic Shape: (801, 8)

In [3]:
def dataset_info(df, name):

    print("="*80)
    print(name.upper())
    print("="*80)

    print("\nFirst Five Rows")
    print(df.head())

    print("\nDataset Shape")
    print(df.shape)

    print("\nRows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\nColumn Names")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nInformation")
    print(df.info())

In [4]:
def missing_values(df):

    missing = pd.DataFrame({
        'Missing Values': df.isnull().sum(),
        'Percentage': round(df.isnull().mean()*100,2)
    })

    missing = missing.sort_values(
        by='Missing Values',
        ascending=False
    )

    return missing

In [5]:
print(missing_values(transactions))

print(missing_values(products))

print(missing_values(demographics))

                   Missing Values  Percentage
household_key                   0         0.0
BASKET_ID                       0         0.0
DAY                             0         0.0
PRODUCT_ID                      0         0.0
QUANTITY                        0         0.0
SALES_VALUE                     0         0.0
STORE_ID                        0         0.0
RETAIL_DISC                     0         0.0
TRANS_TIME                      0         0.0
WEEK_NO                         0         0.0
COUPON_DISC                     0         0.0
COUPON_MATCH_DISC               0         0.0
                      Missing Values  Percentage
PRODUCT_ID                         0         0.0
MANUFACTURER                       0         0.0
DEPARTMENT                         0         0.0
BRAND                              0         0.0
COMMODITY_DESC                     0         0.0
SUB_COMMODITY_DESC                 0         0.0
CURR_SIZE_OF_PRODUCT               0         0.0
                     Missing Values  Percentage
AGE_DESC                          0         0.0
MARITAL_STATUS_CODE               0         0.0
INCOME_DESC                       0         0.0
HOMEOWNER_DESC                    0         0.0
HH_COMP_DESC                      0         0.0
HOUSEHOLD_SIZE_DESC               0         0.0
KID_CATEGORY_DESC                 0         0.0
household_key                     0         0.0

In [6]:
def duplicate_info(df,name):

    print("="*60)

    print(name)

    print("Duplicate Rows:",df.duplicated().sum())

    print("Duplicate Percentage:",
          round(df.duplicated().mean()*100,2),"%")

In [7]:
duplicate_info(transactions,"Transactions")

duplicate_info(products,"Products")

duplicate_info(demographics,"Demographics")

============================================================
Transactions
Duplicate Rows: 0
Duplicate Percentage: 0.0 %
============================================================
Products
Duplicate Rows: 0
Duplicate Percentage: 0.0 %
============================================================
Demographics
Duplicate Rows: 0
Duplicate Percentage: 0.0 %

In [8]:
def unique_values(df):

    unique = pd.DataFrame({
        "Unique Values":df.nunique()
    })

    return unique.sort_values(
        by="Unique Values",
        ascending=False
    )

In [9]:
unique_values(transactions)

unique_values(products)

unique_values(demographics)

                     Unique Values
household_key                  801
INCOME_DESC                     12
HH_COMP_DESC                     6
AGE_DESC                         6
HOUSEHOLD_SIZE_DESC              5
HOMEOWNER_DESC                   5
KID_CATEGORY_DESC                4
MARITAL_STATUS_CODE              3

In [10]:
transactions.describe().T

,count,mean,std,min,25%,50%,75%,max
household_key,2595732.0,1.271953e+03,7.260660e+02,1.000000e+00,6.560000e+02,1.272000e+03,1.913000e+03,2.500000e+03
BASKET_ID,2595732.0,3.402620e+10,4.711649e+09,2.698485e+10,3.040805e+10,3.276081e+10,4.012685e+10,4.230536e+10
DAY,2595732.0,3.887562e+02,1.897210e+02,1.000000e+00,2.290000e+02,3.900000e+02,5.530000e+02,7.110000e+02
PRODUCT_ID,2595732.0,2.891435e+06,3.837404e+06,2.567100e+04,9.174590e+05,1.028816e+06,1.133018e+06,1.831630e+07
QUANTITY,2595732.0,1.004286e+02,1.153436e+03,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,8.963800e+04
SALES_VALUE,2595732.0,3.104120e+00,4.182274e+00,0.000000e+00,1.290000e+00,2.000000e+00,3.490000e+00,8.400000e+02
STORE_ID,2595732.0,3.142673e+03,8.937113e+03,1.000000e+00,3.300000e+02,3.720000e+02,4.220000e+02,3.428000e+04
RETAIL_DISC,2595732.0,-5.387054e-01,1.249191e+00,-1.800000e+02,-6.900000e-01,-1.000000e-02,0.000000e+00,3.990000e+00
TRANS_TIME,2595732.0,1.561586e+03,3.998378e+02,0.000000e+00,1.308000e+03,1.613000e+03,1.843000e+03,2.359000e+03
WEEK_NO,2595732.0,5.622150e+01,2.710223e+01,1.000000e+00,3.300000e+01,5.600000e+01,8.000000e+01,1.020000e+02
COUPON_DISC,2595732.0,-1.641600e-02,2.168410e-01,-5.593000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
COUPON_MATCH_DISC,2595732.0,-2.918564e-03,3.969004e-02,-7.700000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [11]:
products.describe().T

,count,mean,std,min,25%,50%,75%,max
PRODUCT_ID,92353.0,5.328353e+06,5.359937e+06,25671.0,970628.0,1621091.0,9704770.0,18316298.0
MANUFACTURER,92353.0,1.739228e+03,1.818270e+03,1.0,328.0,1094.0,2264.0,6477.0

In [12]:
demographics.describe().T

,count,mean,std,min,25%,50%,75%,max
household_key,801.0,1235.17603,736.804647,1.0,596.0,1218.0,1914.0,2499.0

In [14]:
products.describe(include='object').T

                      count unique                             top   freq
DEPARTMENT            92353     44                         GROCERY  39021
BRAND                 92353      2                        National  78537
COMMODITY_DESC        92353    308  GREETING CARDS/WRAP/PARTY SPLY   2785
SUB_COMMODITY_DESC    92353   2383                  CARDS EVERYDAY   1005
CURR_SIZE_OF_PRODUCT  92353   4345                                  30607

In [15]:
demographics.describe(include='object').T

                    count unique               top freq
AGE_DESC              801      6             45-54  288
MARITAL_STATUS_CODE   801      3                 U  344
INCOME_DESC           801     12            50-74K  192
HOMEOWNER_DESC        801      5         Homeowner  504
HH_COMP_DESC          801      6  2 Adults No Kids  255
HOUSEHOLD_SIZE_DESC   801      5                 2  318
KID_CATEGORY_DESC     801      4      None/Unknown  558

In [16]:
def datatype_summary(df):

    print(df.dtypes.value_counts())

In [17]:
datatype_summary(transactions)

datatype_summary(products)

datatype_summary(demographics)

int64      8
float64    4
Name: count, dtype: int64
object    5
int64     2
Name: count, dtype: int64
object    7
int64     1
Name: count, dtype: int64

In [18]:
def datatype_summary(df):

    print(df.dtypes.value_counts())

In [19]:
datatype_summary(transactions)

datatype_summary(products)

datatype_summary(demographics)

int64      8
float64    4
Name: count, dtype: int64
object    5
int64     2
Name: count, dtype: int64
object    7
int64     1
Name: count, dtype: int64

In [20]:
transactions.columns

Index(['household_key', 'BASKET_ID', 'DAY', 'PRODUCT_ID', 'QUANTITY',
       'SALES_VALUE', 'STORE_ID', 'RETAIL_DISC', 'TRANS_TIME', 'WEEK_NO',
       'COUPON_DISC', 'COUPON_MATCH_DISC'],
      dtype='object')

In [21]:
transactions['SALES_VALUE'].describe()

count    2.595732e+06
mean     3.104120e+00
std      4.182274e+00
min      0.000000e+00
25%      1.290000e+00
50%      2.000000e+00
75%      3.490000e+00
max      8.400000e+02
Name: SALES_VALUE, dtype: float64

In [22]:
correlation = transactions.select_dtypes(include=np.number).corr()

sales_corr = correlation['SALES_VALUE'].sort_values(
    ascending=False
)

print(sales_corr)

SALES_VALUE          1.000000
QUANTITY             0.587993
PRODUCT_ID           0.127372
DAY                  0.012710
WEEK_NO              0.012691
BASKET_ID            0.011574
household_key        0.005125
COUPON_MATCH_DISC    0.003618
STORE_ID            -0.001428
TRANS_TIME          -0.016987
COUPON_DISC         -0.037573
RETAIL_DISC         -0.250082
Name: SALES_VALUE, dtype: float64

In [23]:
numeric = transactions.select_dtypes(include=np.number)

for col in numeric.columns:

    if col != 'SALES_VALUE':

        corr = transactions[col].corr(
            transactions['SALES_VALUE']
        )

        print(f"{col:<25} {corr:.4f}")

household_key             0.0051
BASKET_ID                 0.0116
DAY                       0.0127
PRODUCT_ID                0.1274
QUANTITY                  0.5880
STORE_ID                  -0.0014
RETAIL_DISC               -0.2501
TRANS_TIME                -0.0170
WEEK_NO                   0.0127
COUPON_DISC               -0.0376
COUPON_MATCH_DISC         0.0036

In [24]:
transactions.groupby('STORE_ID')['SALES_VALUE'].mean().sort_values(ascending=False)

STORE_ID
3065    72.000000
489     51.600000
86      50.820000
3098    43.620000
1162    41.000000
          ...
2825     0.513333
751      0.512857
610      0.500000
639      0.425000
1235     0.000000
Name: SALES_VALUE, Length: 582, dtype: float64

In [25]:
categorical = transactions.select_dtypes(include='object').columns

for col in categorical:

    print("="*60)

    print(col)

    print(transactions.groupby(col)['SALES_VALUE'].mean().sort_values(ascending=False).head(10))

In [26]:
cardinality = pd.DataFrame({

    'Unique Values':transactions.nunique(),

    'Cardinality %':
    round(transactions.nunique()/len(transactions)*100,2)

})

cardinality.sort_values(
    by='Unique Values',
    ascending=False
)

                   Unique Values  Cardinality %
BASKET_ID                 276484          10.65
PRODUCT_ID                 92339           3.56
QUANTITY                   11746           0.45
SALES_VALUE                 5502           0.21
household_key               2500           0.10
RETAIL_DISC                 2414           0.09
TRANS_TIME                  1440           0.06
DAY                          711           0.03
STORE_ID                     582           0.02
COUPON_DISC                  415           0.02
WEEK_NO                      102           0.00
COUPON_MATCH_DISC             80           0.00

In [27]:
zero_values = (transactions==0).sum()

zero_values.sort_values(ascending=False)

COUPON_MATCH_DISC    2578283
COUPON_DISC          2559310
RETAIL_DISC          1292670
SALES_VALUE            18850
QUANTITY               14466
TRANS_TIME               443
BASKET_ID                  0
household_key              0
PRODUCT_ID                 0
DAY                        0
STORE_ID                   0
WEEK_NO                    0
dtype: int64

In [28]:
constant = [col for col in transactions.columns
            if transactions[col].nunique()==1]

constant

[]

In [29]:
def complete_summary(df,name):

    summary = pd.DataFrame({

        "Data Type":df.dtypes,

        "Missing":df.isnull().sum(),

        "Missing %":round(df.isnull().mean()*100,2),

        "Unique":df.nunique(),

        "Duplicates":df.duplicated().sum()

    })

    print("="*80)

    print(name)

    print("="*80)

    return summary

In [30]:
complete_summary(transactions,"Transactions")

================================================================================
Transactions
================================================================================

                  Data Type  Missing  Missing %  Unique  Duplicates
household_key         int64        0        0.0    2500           0
BASKET_ID             int64        0        0.0  276484           0
DAY                   int64        0        0.0     711           0
PRODUCT_ID            int64        0        0.0   92339           0
QUANTITY              int64        0        0.0   11746           0
SALES_VALUE         float64        0        0.0    5502           0
STORE_ID              int64        0        0.0     582           0
RETAIL_DISC         float64        0        0.0    2414           0
TRANS_TIME            int64        0        0.0    1440           0
WEEK_NO               int64        0        0.0     102           0
COUPON_DISC         float64        0        0.0     415           0
COUPON_MATCH_DISC   float64        0        0.0      80           0

In [31]:
complete_summary(products,"Products")

================================================================================
Products
================================================================================

                     Data Type  Missing  Missing %  Unique  Duplicates
PRODUCT_ID               int64        0        0.0   92353           0
MANUFACTURER             int64        0        0.0    6476           0
DEPARTMENT              object        0        0.0      44           0
BRAND                   object        0        0.0       2           0
COMMODITY_DESC          object        0        0.0     308           0
SUB_COMMODITY_DESC      object        0        0.0    2383           0
CURR_SIZE_OF_PRODUCT    object        0        0.0    4345           0

In [32]:
complete_summary(demographics,"Demographics")

================================================================================
Demographics
================================================================================

                    Data Type  Missing  Missing %  Unique  Duplicates
AGE_DESC               object        0        0.0       6           0
MARITAL_STATUS_CODE    object        0        0.0       3           0
INCOME_DESC            object        0        0.0      12           0
HOMEOWNER_DESC         object        0        0.0       5           0
HH_COMP_DESC           object        0        0.0       6           0
HOUSEHOLD_SIZE_DESC    object        0        0.0       5           0
KID_CATEGORY_DESC      object        0        0.0       4           0
household_key           int64        0        0.0     801           0